### ISSUE TITLE
Adding a dependency structure to CITS

### ISSUE THREAD

**Issue by Swoy** [DILCISBoard/SIARD-CITS#1]
I would like to open a discussion around how dependencies could be handled in the future. From a preservation point of view, I would always recommend that dependencies follow the storage media in favor of the actual archive packages, but this cannot always be realized and we should maybe look at ways to reference/include them in the CITS structure.

If we look at how LaTeX is implemented, it would be easy to have classes and style files for templates located inside the structure in a "dependency" folder. In this specific case it doesn't make sense to include them on the medium, but rather in the archives 
themselves.

Using LaTeX further as an example; we could include xml files in this folder, that reference where the binaries are located on the storage media. As mentioned, it is sometimes not possible to have these stored on the media itself, in which case they will have to be present inside the archive package.

![image](https://user-images.githubusercontent.com/5272077/97478969-fba6f380-1951-11eb-9097-fa1dc1004d8f.png)

Do any of you have any thoughts on this?

**Comment by PhillipTommerholt** [comment]
First of all thank you for your input!
According to CSIP it is certainly possibly to add extra folders, so from a information package structure point of view I see no obstacles.

I am not sure what kind of dependencies you mean though, and I am not sure what you mean by medium or by archive. I hope we can discuss this first, so we are on the same lines.
Do you mean "information package" when you say medium? And by "archive" you mean the organisation/institution? And is this issue related to preservation of relational databases or is it a more general aspect? If it is more general, then I would suggest you raise this issue at the CSIP (Common Specification for Information Packages) GitHub repo: https://github.com/DILCISBoard/E-ARK-CSIP 
CSIP specifiation https://earkcsip.dilcis.eu/

_Best regards
Phillip Tømmerholt
Danish National Archives_

**Comment by Swoy** [comment]
Thank you for the quick reply!

When I talk about dependencies, I generally talk about items that could be required to either view or consolidate data inside the database. One such example is database views generated after the fact (by us in the institutions), or in cases where lobs contain content that has external dependencies (from business logic) to make sense of the content.

To clear up the misunderstanding; medium = storage media, archive meaning the actual archive package.

**Comment by PhillipAasvangTommerholt** [comment]
I am closing this. Feel free to open a new issue if you want to further discuss this.
_Best regards
Phillip Tømmerholt
KMD Archiving_
